### ISSUE TITLE
Give appropriate CSS/layout properties to all items in the top banner

### ISSUE THREAD

**Issue by spentak** [devslopes/cacheout#4]
Some of these items aren't properly aligned and spaced. Fix to meet UI specifications

<img width="1279" alt="screen shot 2018-03-13 at 8 04 39 pm" src="https://user-images.githubusercontent.com/758121/37381353-e3d5f56e-26f9-11e8-92c4-c05713a300ea.png">

**Comment by stuhoffman** [comment]
Done with this.
